databases:
  - name: marketstore-db
    databaseName: marketstoredb
    user: marketstoreuser
    plan: free
    region: oregon

services:
  - type: web
    name: marketstore
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marketstore-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: 'False'
      - key: PYTHON_VERSION
        value: 3.10.13

