name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Verify current directory
        run: pwd && ls -al

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-dev libffi-dev libssl-dev build-essential

      - name: Install Python dependencies
        run: |
          cd ${{ github.workspace }}
          echo "Installing from: $(pwd)"
          ls -al
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run Django checks
        run: python manage.py check
      - name: Run Django tests
        run: python manage.py test config.tests.test_basic

